# Generated by Django 4.2.6 on 2023-11-21 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Creators',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FullName', models.CharField(max_length=50)),
                ('UsrName', models.CharField(max_length=50)),
                ('MusicRole', models.CharField(max_length=10)),
                ('Country', models.CharField(max_length=10)),
                ('Email', models.EmailField(max_length=50, unique=True)),
                ('Password', models.CharField(max_length=100)),
                ('Profile_Picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures/')),
                ('Profile_Banner', models.ImageField(blank=True, null=True, upload_to='profile_banners/')),
                ('doj', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
