# Generated by Django 4.2.6 on 2023-11-27 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Creator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Albums',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Album_Name', models.CharField(max_length=50)),
                ('Album_Cover', models.ImageField(blank=True, null=True, upload_to='Creator/Album_Covers')),
            ],
        ),
    ]
