# Generated by Django 4.2.6 on 2023-11-27 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Creator', '0002_albums'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Albums',
        ),
    ]
