# Generated by Django 4.2.6 on 2023-11-27 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Creator', '0003_delete_albums'),
    ]

    operations = [
        migrations.CreateModel(
            name='Albums',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Album_Name', models.CharField(max_length=50)),
                ('Album_Cover', models.ImageField(blank=True, null=True, upload_to='Creator/Album_Covers')),
                ('CrId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Creator.creators')),
            ],
        ),
    ]
