# Generated by Django 4.2.6 on 2023-12-02 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Creator', '0006_music'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Music',
        ),
    ]
