# Generated by Django 4.2.6 on 2023-12-02 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0002_musicmood'),
        ('Creator', '0007_delete_music'),
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('audio_file', models.FileField(upload_to='music/')),
                ('release_date', models.DateField()),
                ('cover_art', models.ImageField(upload_to='music_covers/')),
                ('Album', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Creator.albums')),
                ('CrId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Creator.creators')),
                ('Language', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AdminApp.language')),
                ('Mood', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AdminApp.musicmood')),
                ('collaborator_1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collaborator_1', to='Creator.creators')),
                ('collaborator_2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collaborator_2', to='Creator.creators')),
                ('genre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AdminApp.genre')),
            ],
        ),
    ]
