# Generated by Django 4.2.6 on 2023-12-16 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Creator', '0008_music'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrPlaylist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PlaylistName', models.CharField(max_length=50)),
                ('Playlist_Cover', models.ImageField(blank=True, null=True, upload_to='Creator/CrPlaylist')),
                ('PlStatus', models.IntegerField(default=0)),
                ('CrrId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Creator.creators')),
            ],
        ),
    ]
