# Generated by Django 4.2.6 on 2023-12-16 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Creator', '0009_crplaylist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crplaylist',
            old_name='CrrId',
            new_name='CrId',
        ),
    ]
