# Generated by Django 4.2.6 on 2023-12-16 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Creator', '0010_rename_crrid_crplaylist_crid'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrPlaylistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CrPlid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Creator.crplaylist')),
                ('MusicId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Creator.music')),
            ],
        ),
    ]
