# Generated by Django 4.2.6 on 2023-12-17 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Creator', '0011_crplaylistitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='Crrole',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='music',
            name='c1role',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='music',
            name='c2role',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='music',
            name='c3role',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='music',
            name='collaborator_3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collaborator_3', to='Creator.creators'),
        ),
    ]
