# Generated by Django 4.2.6 on 2023-12-27 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Creator', '0012_music_crrole_music_c1role_music_c2role_music_c3role_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Msg', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('Crid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Creator.creators')),
            ],
        ),
    ]
