# Generated by Django 4.2.6 on 2023-12-27 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Creator', '0013_notifications'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notifications',
        ),
    ]
