# Generated by Django 4.2.6 on 2023-12-27 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Creator', '0014_delete_notifications'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Msg', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('Crid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_receiver', to='Creator.creators')),
                ('FlwCrid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_generator', to='Creator.creators')),
            ],
        ),
    ]
