# Generated by Django 4.2.6 on 2024-01-02 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Creator', '0015_notifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='Album',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Creator.albums'),
        ),
    ]
