# Generated by Django 4.2.6 on 2023-11-21 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Genre_Name', models.CharField(max_length=50)),
                ('Genre_Icons', models.ImageField(blank=True, null=True, upload_to='Genre_Icons/')),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Lang', models.CharField(max_length=50)),
                ('Lang_Char', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
