# Generated by Django 4.2.6 on 2024-01-03 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0002_musicmood'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admindata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail', models.EmailField(max_length=254, unique=True)),
                ('Password', models.CharField(max_length=150)),
            ],
        ),
    ]
