# Generated by Django 4.2.6 on 2023-11-24 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_formuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formuser',
            name='name',
        ),
        migrations.AddField(
            model_name='formuser',
            name='U_name',
            field=models.CharField(default=12, max_length=50),
            preserve_default=False,
        ),
    ]
