# Generated by Django 4.2.6 on 2023-11-24 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_remove_formuser_name_formuser_u_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FormUser',
        ),
    ]
