# Generated by Django 4.2.6 on 2023-11-24 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0006_delete_formuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('U_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='UserPictures/Profile')),
                ('bannerimage', models.ImageField(blank=True, null=True, upload_to='UserPictures/Banner')),
                ('date_joined', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
