# Generated by Django 4.2.6 on 2023-11-24 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0007_formuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FormUser',
        ),
    ]
