# Generated by Django 4.2.6 on 2023-11-24 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0009_formuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='formuser',
            name='usr_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
