# Generated by Django 4.2.6 on 2023-12-10 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0010_formuser_usr_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PlaylistName', models.CharField(max_length=50)),
                ('Playlist_Cover', models.ImageField(blank=True, null=True, upload_to='User/Playlist')),
                ('UsrId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.formuser')),
            ],
        ),
    ]
