# Generated by Django 4.2.6 on 2023-12-12 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Creator', '0008_music'),
        ('User', '0011_playlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaylistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MusicId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Creator.music')),
                ('Plid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.playlist')),
            ],
        ),
    ]
