# Generated by Django 4.2.6 on 2023-12-12 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0012_playlistitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PlaylistItem',
        ),
    ]
