# Generated by Django 4.2.6 on 2023-12-23 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Creator', '0012_music_crrole_music_c1role_music_c2role_music_c3role_and_more'),
        ('User', '0014_playlistitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowCr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_followed', models.DateTimeField(auto_now_add=True)),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following_User', to='User.formuser')),
                ('following', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followed_Creator', to='Creator.creators')),
            ],
        ),
    ]
